### ISSUE TITLE
message not sended

### ISSUE THREAD

**Issue by Sanan-84** [sadiqodho/GSM-Helper-Tool#1]
Code:
$url='http://'.$setting_data['url'].'/SendSMS?username='.$setting_data['username'].'&password='.$setting_data['password'].'&phone='.$num.'&message='.$p_message;
$curl=curl_init($url);
curl_setopt($curl,CURLOPT_RETURNTRANSFER, true);
$curl_response=curl_exec($curl);
if($curl_response === false){
	$info=curl_getinfo($curl);
	curl_close($curl);
	/*die('Error occurred'.var_export($info));*/
	$output=['error'=>true,'num'=>$num,'message'=>'Error occurred'.var_export($info)];
}else{
	curl_close($curl);
	$response=json_decode($curl_response); 
	if($response->status == 200){$output=['success'=>true,'num'=>$num,'message'=>'Message has been sent'];}
    else{$output=['error'=>true,'num'=>$num,'message'=>'Technical Problem'];}
}

Result:
array (
  'url' => 'http://192.168.3.222:4477/sendSMS?username=webservis.az&password=Sanan1984&phone=0557054477&message=aaaa',
  'content_type' => NULL,
  'http_code' => 0,
  'header_size' => 0,
  'request_size' => 0,
  'filetime' => -1,
  'ssl_verify_result' => 0,
  'redirect_count' => 0,
  'total_time' => 20.219,
  'namelookup_time' => 1.0E-6,
  'connect_time' => 0.0,
  'pretransfer_time' => 0.0,
  'size_upload' => 0.0,
  'size_download' => 0.0,
  'speed_download' => 0.0,
  'speed_upload' => 0.0,
  'download_content_length' => -1.0,
  'upload_content_length' => -1.0,
  'starttransfer_time' => 0.0,
  'redirect_time' => 0.0,
  'redirect_url' => '',
  'primary_ip' => '',
  'certinfo' => 
  array (
  ),
  'primary_port' => 0,
  'local_ip' => '',
  'local_port' => 0,
){"error":true,"num":"0557054477","message":"Error occurred"}

help...

**Comment by sadiqodho** [comment]
It looks like that your mobile device and your computer is not on the same network. Both should be on same network so that they can communicate via IP address with given port number.
